# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cfcadcba4a03ea4170e29f4eb95215ecc710ed670f68cb605550dc7e0b31266a3311c03f5645648525757fcd96204501d6de933044684a2e06978aefaf86fd49

test:
  secret_key_base: 74f47ad389ba4cff8fc81697f4fe6125a1ac18341bdc8e43c1d4db57d38114344d9578a36936c7b6425167ad75eb41f8439d2028cf298fa735b2e633b079efc6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
